Prep Javascript Loops
Garcia-Tony/javascript-prep-0424-code-solutions pull request #10
Opened 2024-04-30 03:10 UTC by Garcia-Tony

<img width="768" alt="Screen Shot 2024-04-29 at 8 07 21 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/012aee50-4eaf-44a9-b0b6-62cbe3a59986">
<img width="765" alt="Screen Shot 2024-04-29 at 8 07 48 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/b471cd9d-8fbd-4f70-bcd5-c70a9153f5fb">
<img width="751" alt="Screen Shot 2024-04-29 at 8 08 17 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/652da653-dcb6-4036-8830-64c8ac4c377e">
<img width="764" alt="Screen Shot 2024-04-29 at 8 08 44 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/8d0a33aa-51b6-462c-9981-f434870cebbd">
<img width="770" alt="Screen Shot 2024-04-29 at 8 09 26 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/21491972-bb76-482c-93d4-fb5236b790f6">

2024-04-30 21:06 UTC, Zhiwutian requested changes
Some updates are required. 

Make sure that when you create a new array in the function, you define an empty array and then populate it using the loop.

Reach out if you have questions!

2024-04-30 21:06 UTC, Zhiwutian commented on prep-javascript-loops/main.js
> +  const numArray = [0, 1, 2, 3, 4, 5, 6, 7, 8];
this array should be empty when its defined. 
The loop should be populating it.

2024-04-30 21:06 UTC, Zhiwutian commented on prep-javascript-loops/main.js
> +  while (index < 9) index++;
this loop is not currently working. 

Make sure to retest after clearing out the array above.

2024-04-30 21:06 UTC, Zhiwutian commented on prep-javascript-loops/main.js
> +  const numArray = [0, 2, 4, 6, 8, 10, 12, 14, 16];
same as above, this array should be empty when it is defined.

2024-04-30 21:06 UTC, Zhiwutian commented on prep-javascript-loops/main.js
> +  while (index < 18) index++;
this loop will need to be updated.

2024-04-30 21:06 UTC, Zhiwutian commented on prep-javascript-loops/main.js
> +  const numArray = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
same as above, this array should start empty

2024-04-30 21:06 UTC, Zhiwutian commented on prep-javascript-loops/main.js
> +  for (let index = 0; index < 10; index++) return numArray;
This loop should be used to populate the numArray.

2024-04-30 21:06 UTC, Zhiwutian commented on prep-javascript-loops/main.js
> +var forLoops2 = forLoop2('stringVal' + 101);
this function should not be called with an argument.

2024-05-01 02:46 UTC, Garcia-Tony commented
<img width="654" alt="Screen Shot 2024-04-30 at 7 46 06 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/a4166f87-c8cc-4133-b7cc-ef4a258b0964">

2024-05-01 03:31 UTC, Zhiwutian approved these changes
👍🏼

2024-05-07 01:19 UTC, merged