Prep HTML Script Tag -Anthony Garcia
Garcia-Tony/javascript-prep-0424-code-solutions pull request #3
Opened 2024-04-20 20:30 UTC by Garcia-Tony

<img width="695" alt="Screen Shot 2024-04-20 at 1 30 29 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/b8a8f723-b2f4-4914-816d-aa25104c3e30">

2024-04-22 15:44 UTC, Zhiwutian requested changes
small update needed. Let me know if you have any questions around it!

2024-04-22 15:44 UTC, Zhiwutian commented on prep-html-script-tag/index.html
> +      console.log('I have added a script file via the src attribute!');
you want to put this console log into the `main.js` file.

That will allow the script tag on line 10 to run the code from that file

2024-04-23 03:12 UTC, Garcia-Tony commented
<img width="696" alt="Screen Shot 2024-04-22 at 8 12 01 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/85c253dd-1486-42dd-9845-d3b0fed34975">

2024-04-23 03:28 UTC, Zhiwutian approved these changes

2024-04-24 01:14 UTC, merged