Prep Javascript Variables - Anthony Garcia
Garcia-Tony/javascript-prep-0424-code-solutions pull request #4
Opened 2024-04-20 21:48 UTC by Garcia-Tony

<img width="721" alt="Screen Shot 2024-04-20 at 2 47 23 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/2ec9bf5b-3c01-4f02-8324-9cdb8eaaa70e">

2024-04-22 15:47 UTC, Zhiwutian requested changes
tiny update needed. 

Great work so far!

2024-04-22 15:47 UTC, Zhiwutian commented on prep-javascript-variables/index.html
> +      let = undefined;
make sure you add a `variable` here

let nothing = undefined

2024-04-23 03:15 UTC, Garcia-Tony commented
<img width="648" alt="Screen Shot 2024-04-22 at 8 14 14 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/ea362c95-ab5d-472f-8fcf-d85ee5038be0">
<img width="336" alt="Screen Shot 2024-04-22 at 8 14 54 PM" src="https://github.com/Garcia-Tony/javascript-prep-0424-code-solutions/assets/166793944/775526fd-7142-41aa-b3ca-0e04add0a745">

2024-04-23 16:02 UTC, Zhiwutian approved these changes
this does work, but in the future, I would only use one `script` tag to hold all of the JS

2024-04-24 01:13 UTC, merged